import { SplashScreen } from "@/components/splash-screen";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({ subsets: ['latin'], weight: ['400', '600', '700'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <html lang="pt-BR" suppressHydrationWarning >
      <body
        suppressHydrationWarning
        className={`${inter.className} antialiased`}
      >
        <Suspense fallback={<SplashScreen />}>
          <Providers>
            {children}
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
